### ISSUE TITLE
Problem with "client components"

### ISSUE THREAD

**Issue by alexllao** [amannn/next-intl-example-next-13#1]
Hi!

1.) 
I have the same project but I'm also trying to use the useTranslations hook in a component that only runs on the client (with the "use client" directive). It always gives me an error: Error: No intl context found. Have you configured the provider?

How could it be solved?

I think ni that case the best aproach is pass translations in Component props, but i'm not sure about this.

2.) Error when "dynamic server usage":

`// src\app\[locale]\news\[slug]\page.js

import { useTranslations } from "next-intl";
import PageLayout from "@/components/PageLayout";

export default function Index({ params: { slug} }) {
    const t = useTranslations("News");

    return (
        <PageLayout title={t("title")}>
            <p>slug: {slug}</p>
        </PageLayout>
    );
}

export async function generateStaticParams() {
    return [{ slug: "test1" }, { slug: "test2" }];
}
`

This a simple code. When I run it, it tells me an error using Dynamic Server.

![imagen](https://user-images.githubusercontent.com/8004573/225852950-8a6a905d-0ef0-46ff-a9f7-20e5aae284be.png)

Thank you.

**Comment by amannn** [comment]
Hi @alexllao and thank you for the question! There's a [section about this in the docs](https://next-intl-docs.vercel.app/docs/next-13/server-components#using-translations-in-client-components) that should hopefully answer your question (incl. the article mentioned there). Let me know if something is unclear!

**Comment by alexllao** [comment]
Hi!!!

Second issue is not mentioned.

Error when "dynamic server usage":

`// src\app[locale]\news[slug]\page.js

import { useTranslations } from "next-intl";
import PageLayout from "@/components/PageLayout";

export default function Index({ params: { slug} }) {
const t = useTranslations("News");

return (
    <PageLayout title={t("title")}>
        <p>slug: {slug}</p>
    </PageLayout>
);

}

export async function generateStaticParams() {
return [{ slug: "test1" }, { slug: "test2" }];
}
`

This a simple code. When I run it, it tells me an error using Dynamic Server.

![imagen](https://user-images.githubusercontent.com/8004573/225862207-917999e6-dd8e-4ae8-8faf-3cda7235fd9b.png)


Thank you.

**Comment by amannn** [comment]
This is covered in the roadmap: https://next-intl-docs.vercel.app/docs/next-13/server-components#roadmap. The next beta version will include a better error message for this case, thanks for bringing it up!
