### ISSUE TITLE
How to use my custom middleware + intl middleware without conflicts?

### ISSUE THREAD

**Issue by velychkodmytro20** [amannn/next-intl-example-next-13#2]
Hi, maybe you know how to use multiple middlewares together? I use your example middleware + my custom auth middleware with protected routes

And they both conflicts with each-other
I can make works just one of middlewares, but not both of them

**Comment by amannn** [comment]
Hi @velychkodmytro20!

It's unfortunately hard for me to know what the issue is here with the limited amount of information available. There's been some discussion on composing middlewares here: https://github.com/amannn/next-intl/pull/149#issuecomment-1471592626 (and the comments below).

I haven't had time to explore this topic in more detail, but generally, it should be possible. If you happen to find a solution, it would be really cool if you could share it!

**Comment by velychkodmytro20** [comment]
> Hi @velychkodmytro20!
> 
> It's unfortunately hard for me to know what the issue is here with the limited amount of information available. There's been some discussion on composing middlewares here: [amannn/next-intl#149 (comment)](https://github.com/amannn/next-intl/pull/149#issuecomment-1471592626) (and the comments below).
> 
> I haven't had time to explore this topic in more detail, but generally, it should be possible. If you happen to find a solution, it would be really cool if you could share it!

Yes, I found a simple way to do it, but this solutions may not be suitable for other users
The main idea, as I understood is to make just one main function middleware for the whole application

And If you need, for example, a middleware for roles auth and internalization middleware, you should just do it in one middleware function and export it

I did just smth like this
if(pathname === 'admin') {
       ....do smth
       }
In other way just do your internalization functionality

Or if you need to make admin page also internalizated
`const intl = ... do smth for internalization`
`If (pathname === 'admin') { 
              `... do smth for admin middleware AND in the end make intl() call for internalization the admin page`
              `}`
 `intl() // in the end of middleware function`

**Comment by amannn** [comment]
Thank you for describing your solution!

I've now created an issue on the main repo to track the composing middlewares documentation: https://github.com/amannn/next-intl/issues/247. Feel free to join the conversation there!
